# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='todo',
  syntax='proto3',
  serialized_pb=_b('\n\rservice.proto\x12\x04todo\"\"\n\x05Tasks\x12\x19\n\x05tasks\x18\x01 \x03(\x0b\x32\n.todo.Task\"I\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x64one\x18\x04 \x01(\t\"\x1c\n\nTaskStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1e\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xe8\x01\n\x04ToDo\x12&\n\x08GetTasks\x12\x0b.todo.Empty\x1a\x0b.todo.Tasks\"\x00\x12*\n\x07GetTask\x12\x11.todo.TaskRequest\x1a\n.todo.Task\"\x00\x12,\n\nUpdateTask\x12\n.todo.Task\x1a\x10.todo.TaskStatus\"\x00\x12)\n\x07\x41\x64\x64Task\x12\n.todo.Task\x1a\x10.todo.TaskStatus\"\x00\x12\x33\n\nDeleteTask\x12\x11.todo.TaskRequest\x1a\x10.todo.TaskStatus\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_TASKS = _descriptor.Descriptor(
  name='Tasks',
  full_name='todo.Tasks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='todo.Tasks.tasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=57,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='todo.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='todo.Task.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='todo.Task.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='todo.Task.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done', full_name='todo.Task.done', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=132,
)


_TASKSTATUS = _descriptor.Descriptor(
  name='TaskStatus',
  full_name='todo.TaskStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='todo.TaskStatus.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=162,
)


_TASKREQUEST = _descriptor.Descriptor(
  name='TaskRequest',
  full_name='todo.TaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='todo.TaskRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=194,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='todo.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=203,
)

_TASKS.fields_by_name['tasks'].message_type = _TASK
DESCRIPTOR.message_types_by_name['Tasks'] = _TASKS
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['TaskStatus'] = _TASKSTATUS
DESCRIPTOR.message_types_by_name['TaskRequest'] = _TASKREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tasks = _reflection.GeneratedProtocolMessageType('Tasks', (_message.Message,), dict(
  DESCRIPTOR = _TASKS,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:todo.Tasks)
  ))
_sym_db.RegisterMessage(Tasks)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:todo.Task)
  ))
_sym_db.RegisterMessage(Task)

TaskStatus = _reflection.GeneratedProtocolMessageType('TaskStatus', (_message.Message,), dict(
  DESCRIPTOR = _TASKSTATUS,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:todo.TaskStatus)
  ))
_sym_db.RegisterMessage(TaskStatus)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _TASKREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:todo.TaskRequest)
  ))
_sym_db.RegisterMessage(TaskRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:todo.Empty)
  ))
_sym_db.RegisterMessage(Empty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'))

_TODO = _descriptor.ServiceDescriptor(
  name='ToDo',
  full_name='todo.ToDo',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=206,
  serialized_end=438,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTasks',
    full_name='todo.ToDo.GetTasks',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TASKS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTask',
    full_name='todo.ToDo.GetTask',
    index=1,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTask',
    full_name='todo.ToDo.UpdateTask',
    index=2,
    containing_service=None,
    input_type=_TASK,
    output_type=_TASKSTATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddTask',
    full_name='todo.ToDo.AddTask',
    index=3,
    containing_service=None,
    input_type=_TASK,
    output_type=_TASKSTATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTask',
    full_name='todo.ToDo.DeleteTask',
    index=4,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASKSTATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODO)

DESCRIPTOR.services_by_name['ToDo'] = _TODO

# @@protoc_insertion_point(module_scope)
